<a href="https://colab.research.google.com/github/vigneshavmm/mini_projects/blob/main/r_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a<- read.csv("/content/Data1.csv", stringsAsFactors=FALSE, na.strings = ".")

# Table for DATA
table(a$CANADA)


 556.78  578.76  659.88  665.46  718.98   731.1  844.55  862.21  898.66  974.81 
      1       1       1       1       1       1       1       1       1       1 
 990.55 1150.71 1158.88 1178.66  1205.4 1229.52 1336.67 1399.04 1679.74 
      1       1       1       1       1       1       1       1       1 

In [ ]:
# Sample data frame
data <- data.frame(
  rollno = c(1, 5, 4, 2, 3, 7, 9, 8, 10, 6),
  subjects = c("jay", "priya", "siva", "sai", "abi", "bala", "zara", "john", "arun", "vani"))

# Sort the data frame in decreasing order based on subjects
sorted_data <- data.frame(
  rollno = data$rollno[order(data$subjects, decreasing = TRUE)],
  subjects = data$subjects[order(data$subjects, decreasing = TRUE)])

# Print the sorted data frame
print(sorted_data)

   rollno subjects
1       9     zara
2       6     vani
3       4     siva
4       2      sai
5       5    priya
6       8     john
7       1      jay
8       7     bala
9      10     arun
10      3      abi


In [ ]:
# R Program to combine two lists

# Creating Lists using the list() function
List1 <- list(1, 2, 3)
List2 <- list('a', 'b', 'c')

print(List1)
print(List2)

# Combining lists using c() function
List3 = c(List1, List2)
print(List3)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "a"

[[5]]
[1] "b"

[[6]]
[1] "c"



In [ ]:
data <- c(1, 2, 3, 1, 2, 3, 1, 2, 3)
A <- matrix(data, nrow = 3, ncol = 3)

data <- c(3, 2, 1, 3, 2, 1, 3, 2, 1)
B <- matrix(data, nrow = 3, ncol = 3)

AB <- A %*% B

print("Matrix A")
print(A)
print("Matrix B")
print(B)
print("Matrix Multiplication Result")
print(AB)

[1] "Matrix A"
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    2    2    2
[3,]    3    3    3
[1] "Matrix B"
     [,1] [,2] [,3]
[1,]    3    3    3
[2,]    2    2    2
[3,]    1    1    1
[1] "Matrix Multiplication Result"
     [,1] [,2] [,3]
[1,]    6    6    6
[2,]   12   12   12
[3,]   18   18   18
